### ISSUE TITLE
Hotkey Glitched while switching input between Keyboard and Gamepad mode

### ISSUE THREAD

**Issue by mTwsnake** [DakJaniels/FancyActionBarPlus#26]
Hotkey display should be under the bottom of the Action Bar, but while i switching input mode from Keyboard to Gamepad, it goes like this after recently update. Before this update normally should only need to /reloadui can reslove it but now can't fix it.
![20240904200917_1](https://github.com/user-attachments/assets/ea63e1a8-68eb-448b-8d64-663b96f3a523)
![20240910073250_1](https://github.com/user-attachments/assets/093bcd41-6e47-43f3-a40d-5c5daf4713c0)
![20240910073257_1](https://github.com/user-attachments/assets/d6272948-ce3b-4680-81bc-475635b3d452)
![20240910073341_1](https://github.com/user-attachments/assets/874508ac-97bc-4ae4-a4f4-2123f5f6ceaa)
![20240910073351_1](https://github.com/user-attachments/assets/157f42bd-9e34-45d5-907d-1c9db8cf033c)
![20240910073422_1](https://github.com/user-attachments/assets/c39343c4-3dfb-47ce-a754-6492c83fa4d7)

**Comment by ACastanza** [comment]
Hi mTwsnake, thanks for bringing this to my attention, since I play with these off it looks like I missed a function call when designing the new force gamepad ui mode. I have a tentative fix now, and it should be included in the next release

**Comment by ACastanza** [comment]
Okay, I'm pretty sure this is fixed with the 2.8.1 version, which I've set as the current release here and uploaded to ESOUI for release through minion.
Let me know if this fixes the issue for you (also, you should no longer need to reloadui to fix it after swapping UI modes either, it should be fixed fixed.)
