### ISSUE TITLE
Icon doesnt change while guarding groupmates

### ISSUE THREAD

**Issue by mTwsnake** [DakJaniels/FancyActionBarPlus#33]
it seems right now even guard to groupmate but dont change the icon to X like before

**Comment by ACastanza** [comment]
Hey, do you know which version this feature was last behaving like you're describing here? If you roll back to that version does it fix the issue? And if so, would you be able to provide a screenshot of the expected behavior?

In the meantime, I'll look into what might've happened here.

**Comment by mTwsnake** [comment]
I think before the latest update should be working fine there, I’m trying to to roll back to last version later today to see if the issue persist or not. U can also try it in game using mystery guard to someone else see if the issue happens or not.

**Comment by mTwsnake** [comment]
![image](https://github.com/user-attachments/assets/8462ef4a-6dc6-4f65-956a-a8a673deafe0)
found the issue where comes from, it's not FAB+, is Lui!
after lui loaded, the mystic guard will not change icon like before

**Comment by ACastanza** [comment]
Yeah, I looked at the FAB behavior and the basegame UI behavior, and Guard only has the toggle highlight. Any icon replacements would have been done by another addon. If LUI's icon replacements broke (I know there was some work recentry on allowing an option to turn them off for people who didn't want them), then I'd ask that you open a new issue on the LUI repo.

**Comment by mTwsnake** [comment]
![image](https://github.com/user-attachments/assets/340d41cf-0bcc-4b7c-9a93-ba741d5e0f4c)
can u copy the enemy marker code from LUI rather than Undaunted?
This floating marker i think is much better than Undaunted one.. is Shinny and noticeable!

**Comment by ACastanza** [comment]
Hello,
I have no intention of making any updates to this feature, the only reason it is there at all is that Noget put it in so it was already there when we took over. I'd just as soon remove it entirely, and only haven't because some people might be relying on it.

**Comment by mTwsnake** [comment]
okie okie! keep up the good work!

**Comment by mTwsnake** [comment]
"I know there was some work recentry on allowing an option to turn them off for people who didn't want them)"
i didnt found any settings to turn the Lui customize icon off, do u have any suggestion?

**Comment by DakJaniels** [comment]
> "I know there was some work recentry on allowing an option to turn them off for people who didn't want them)"
> 
> i didnt found any settings to turn the Lui customize icon off, do u have any suggestion?

I have a fix for LUIE. Working on other things before pushing an update out. Possibly next week if testing goes well. Thanks for your report.
